### ISSUE TITLE
Make use of Bearer auth trait

### ISSUE THREAD

**Issue by shadowhand** [w-takumi/oauth2-base#2]
[`BearerAuthorizationTrait`](https://github.com/thephpleague/oauth2-client/blob/master/src/Tool/BearerAuthorizationTrait.php) can be used instead of [`getAuthorizationHeaders`](https://github.com/w-takumi/oauth2-base/blob/67c5283d7460f1085980b54a498aa94af6e4e300/src/Provider/BaseProvider.php#L98-L101).

**Comment by tanigami** [comment]
@shadowhand Thanks!
