### ISSUE TITLE
Make use of array accessor trait

### ISSUE THREAD

**Issue by shadowhand** [w-takumi/oauth2-base#3]
[`ArrayAccessorTrait`](https://github.com/thephpleague/oauth2-client/blob/master/src/Tool/ArrayAccessorTrait.php) can be used to prevent errors when [reading resource owner properties](https://github.com/w-takumi/oauth2-base/blob/67c5283d7460f1085980b54a498aa94af6e4e300/src/Provider/BaseResourceOwner.php#L31). See [usage in oauth2-github](https://github.com/thephpleague/oauth2-github/blob/b6649ab573216e517056f1bcf23e7293dfc5bf64/src/Provider/GithubResourceOwner.php#L40).

**Comment by tanigami** [comment]
@shadowhand Well that's smart.
